### ISSUE TITLE
Change file extension from .php to .rdf

### ISSUE THREAD

**Issue by acka47** [structureddynamics/Bibliographic-Ontology-BIBO#12]
Currently, I get the following for `$ curl -i http://purl.org/ontology/bibo/`:

```
HTTP/1.1 302 FOUND
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 09 Dec 2016 13:45:02 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 211
Connection: keep-alive
Location: http://bibliographic-ontology.org/bibo/bibo.php
```

The current file extension for the RDF/XML ontology file (`.php`) is really confusing me and probably others. Could you please change it to `.rdf`?

**Comment by fgiasson** [comment]
It is the way the content negotiation is currently handled by the server (and how it works with purl.org). Following this 302 location gives you the actual ontology document. I have no plan to reconfigure the server at that point to remove the .php extension in the 302 `Location:` field.
