### ISSUE TITLE
http://bibliographic-ontology.org/ is down

### ISSUE THREAD

**Issue by acka47** [structureddynamics/Bibliographic-Ontology-BIBO#13]
http://purl.org/ontology/bibo doesn't resolve anymore as bibliographic-ontology.org seems to be down.

```
$ curl -iL http://purl.org/ontology/bibo/ 
HTTP/1.1 302 FOUND
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 30 Jan 2018 11:17:27 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 211
Connection: keep-alive
Location: http://bibliographic-ontology.org/bibo/bibo.php
Access-Control-Allow-Origin: *

curl: (7) Failed to connect to bibliographic-ontology.org port 80
```

**Comment by acka47** [comment]
An easy way to fix the resolving problem would be to reconfigure http://purl.org/ontology/bibo to redirect to https://raw.githubusercontent.com/structureddynamics/Bibliographic-Ontology-BIBO/master/bibo.owl (or preferably a turtle version of the ontology).

**Comment by fgiasson** [comment]
We are now thinking checking with DCMI to host it. Another option I was thinking about is to replace everything by  @dgarijo PR here: https://github.com/structureddynamics/Bibliographic-Ontology-BIBO/pull/14

**Comment by fgiasson** [comment]
Everything should be fixed now, can you confirm?

**Comment by dgarijo** [comment]
I get a 404 when accessing http://purl.org/ontology/bibo

**Comment by fgiasson** [comment]
Hi

Looks like it is missing a ending slash to the URI.

Thanks

Fred

**Comment by dgarijo** [comment]
Normally people use URIs without the final slash, so I would recommend fixing that redirection too. The file at http://purl.org/ontology/bibo/ is served successfully, but without content negotiation :(

**Comment by acka47** [comment]
Yes, it works again the way it did before the downtime. Closing.
