### ISSUE TITLE
http://bibliographic-ontology.org/examples returns 404

### ISSUE THREAD

**Issue by e-e-e** [structureddynamics/Bibliographic-Ontology-BIBO#18]
The example link from main html site is currently pointing to http://bibliographic-ontology.org/examples which returns a 404.

**Comment by e-e-e** [comment]
so does http://bibliographic-ontology.org/specification

**Comment by fgiasson** [comment]
Yes the website is really, really old and barely supported. All this should be replaced and moved to Dublincore. The source of truth at the moment is the Github page for the Ontology.

**Comment by e-e-e** [comment]
Thanks. @fgiasson am I understanding you correctly - that BIBO is basically deprecated and we should prefer Dublincore over this ontology?

**Comment by bdarcus** [comment]
No. Hosting will be handled by DC.

**Comment by fgiasson** [comment]
no, far from it. Like @bdarcus  said, BIBO will be integrated in the Dublincore infrastructure and processes which will guarantee its support and improvement in the coming years/decades.
