### ISSUE TITLE
Review Court Reporter class

### ISSUE THREAD

**Issue by pols12** [structureddynamics/Bibliographic-Ontology-BIBO#19]
Hi!

According to me, “A collection of legal cases.” class comment doesn’t match with “Court Reporter” label.

Is this class supposed to be a [court reporter as defined by Wikipedia](https://en.wikipedia.org/wiki/Court_reporter)?
Or the label should be “CourtReport”?

I’m not English native, but I don’t understand what definitions of “reporter” and “collection” can match.

**Comment by pols12** [comment]
Reporter seems to be used as a synonym for Report (maybe as a metonymy), so a CourtReporter would be a [Law Report on Wikipedia](https://en.wikipedia.org/wiki/Reporter_(law)).
It’s really confusing.

Sorry for my mistake.

**Comment by bdarcus** [comment]
I agree; it is confusing.

But yes, that Wikipedia link fits the meaning here. The first line of it
even says "reports or reporters."
