### ISSUE TITLE
domain name change?

### ISSUE THREAD

**Issue by corined** [structureddynamics/Bibliographic-Ontology-BIBO#22]
Has the ontology changed its domain URL again? I get an error message when I click on:
http://bibliographic-ontology.org 

But this seems to work: http://bibliontology.com/

I thought I was using the correct one ...

Thanks,

Corine Deliot

**Comment by fgiasson** [comment]
Hi @corined,

Yes, BIBO is now under DCMI and shouldn't move anymore. This is a move that Bruce and I did with the DCMI to sustain it for years, decades, to come.
