### ISSUE TITLE
domain name not resolving?

### ISSUE THREAD

**Issue by corined** [structureddynamics/Bibliographic-Ontology-BIBO#9]
Hello,

The bibo ontology seems to have gone offline. The redirect from http://purl.org/ontology/bibo/ goes to this: http://bibliontology.com/bibo/bibo.php# 
The only human readable version I have found is http://neologism.ecs.soton.ac.uk/bibo and I don't know if it is up to date.

Thanks

Corine Deliot

**Comment by fgiasson** [comment]
Hi @corined,

That is right, I noticed that last week. The domain was owned by OpenLinks software, but it experired and it appears that the domain is now in limbo.

I am currently taking the steps to recover it or to create a new one for the community. 

In mean time, I think your best bet is to visualize the ontology in [Protégé](http://protege.stanford.edu/). Sorry for the inconvenient.

Will tell you one this is resolved.

**Comment by fgiasson** [comment]
@corined I just aquired a new domain for BIBO, I will setup it soon and everything should be back as normal afterward. Will keep you updated.

**Comment by fgiasson** [comment]
Fixed, the new domain is http://bibliographic-ontology.org

**Comment by fgiasson** [comment]
Good news, purl.org is not operated by the Web Archive, so the purl.org for BIBO should now point to the right server.
